global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'triton'
    static_configs:
      - targets: ['triton:8002']

  - job_name: 'workers'
    # In a real-world scenario, you would use service discovery.
    # For Docker Compose, we can use DNS round-robin.
    dns_sd_configs:
    - names:
      - 'worker' # Service name in docker-compose
      type: 'A'
      port: 8001